#!/usr/bin/env python3
import argparse
import json
import os
import shutil
import subprocess
import sys

# Add scripts to sys.path to import boards
sys.path.append(os.path.join(os.path.dirname(__file__), "scripts"))
import features
from boards import BOARD_TARGET, SUPPORTED_BOARDS

BOARDS = list(SUPPORTED_BOARDS.keys())

STEPS = ["webapp", "splash", "firmware"]
# "configure" only runs the CMake configure of the firmware (used by scripts/feature_matrix.py)
OPTIONAL_STEPS = ["configure"]

DEFAULT_BUILD_DIR = "build"


def state_file(build_dir):
    """Board + feature set a build directory was configured for. sdkconfig is
    only regenerated by a fresh configure, so a changed set needs a full clean."""
    return os.path.join(build_dir, ".features")


def full_clean(build_dir=DEFAULT_BUILD_DIR):
    """Remove sdkconfig, the generated partition table and the build directory."""
    print("Performing full clean...")
    for f in ["sdkconfig", "partitions.csv"]:
        if build_dir == DEFAULT_BUILD_DIR and os.path.exists(f):
            os.remove(f)
            print(f"  ✓ Removed {f}")
    if os.path.isdir(build_dir):
        shutil.rmtree(build_dir)
        print(f"  ✓ Removed {build_dir}/")


def read_build_state(build_dir=DEFAULT_BUILD_DIR):
    try:
        with open(state_file(build_dir), encoding="utf-8") as f:
            return json.load(f)
    except (OSError, ValueError):
        return None


def write_build_state(state, build_dir=DEFAULT_BUILD_DIR):
    os.makedirs(build_dir, exist_ok=True)
    with open(state_file(build_dir), "w", encoding="utf-8", newline="\n") as f:
        json.dump(state, f, sort_keys=True)


def build_webapp(enabled_features):
    """Build the webapp (npm install + npm run build).

    The enabled features are handed to Vite as VITE_FEATURES so that the bundle
    contains only the UI of the features the firmware was built with.
    """
    print("\n=== Building webapp ===")
    env = dict(os.environ, VITE_FEATURES=",".join(enabled_features))
    try:
        # A native dependency's prebuilt binary download can fail transiently in
        # CI and fall into a compile that the runner can't do; one retry
        # fetches it.
        try:
            subprocess.run("npm install", shell=True, check=True, cwd="webapp")
        except subprocess.CalledProcessError:
            print("  npm install failed, retrying once...", flush=True)
            subprocess.run("npm install", shell=True, check=True, cwd="webapp")
        subprocess.run("npm run build", shell=True, check=True, cwd="webapp", env=env)
    except subprocess.CalledProcessError as e:
        print(f"  ✗ Webapp build failed with exit code {e.returncode}")
        sys.exit(e.returncode)
    except FileNotFoundError:
        print(
            "  ✗ 'npm' not found. Please ensure Node.js is installed and in your PATH."
        )
        sys.exit(1)


def generate_splash(board):
    """Generate splash screen EPDGZ for the target board."""
    print(f"\n=== Generating splash screen for {board} ===", flush=True)
    output_dir = os.path.join(os.path.dirname(__file__), "main", "splash_data")
    script = os.path.join(os.path.dirname(__file__), "scripts", "generate_splash.py")
    process_cli_dir = os.path.join(os.path.dirname(__file__), "process-cli")

    # Ensure process-cli dependencies are installed - and current: npm records what it
    # installed in node_modules/.package-lock.json, so a newer package-lock.json (a
    # checkout that changed the dependencies) means the installed set is stale.
    node_modules = os.path.join(process_cli_dir, "node_modules")
    installed = os.path.join(node_modules, ".package-lock.json")
    lock = os.path.join(process_cli_dir, "package-lock.json")
    stale = (
        os.path.isfile(installed)
        and os.path.isfile(lock)
        and os.path.getmtime(lock) > os.path.getmtime(installed)
    )
    if not os.path.isdir(node_modules) or stale:
        print("  Installing process-cli dependencies...")
        try:
            subprocess.run("npm ci", shell=True, check=True, cwd=process_cli_dir)
        except subprocess.CalledProcessError as e:
            print(f"  ✗ npm ci failed in process-cli with exit code {e.returncode}")
            sys.exit(e.returncode)

    try:
        subprocess.run(
            [sys.executable, script, "--board", board, "--output-dir", output_dir],
            check=True,
        )
    except subprocess.CalledProcessError as e:
        print(f"  ✗ Splash generation failed with exit code {e.returncode}")
        sys.exit(e.returncode)


def idf_py_command():
    """Return the argv prefix that runs idf.py.

    On Windows, CreateProcess cannot execute the idf.py script directly
    (WinError 193). Prefer the idf.py.exe wrapper that the Windows installers
    put on PATH; otherwise run $IDF_PATH/tools/idf.py through the ESP-IDF
    Python interpreter (IDF_PYTHON_ENV_PATH is set by the activation script).
    """
    if os.name != "nt":
        return ["idf.py"]
    found = shutil.which("idf.py")
    if found and found.lower().endswith(".exe"):
        return [found]
    idf_path = os.environ.get("IDF_PATH")
    script = os.path.join(idf_path, "tools", "idf.py") if idf_path else found
    if not script or not os.path.isfile(script):
        return ["idf.py"]  # let subprocess raise FileNotFoundError
    env_path = os.environ.get("IDF_PYTHON_ENV_PATH")
    python = os.path.join(env_path, "Scripts", "python.exe") if env_path else ""
    if not os.path.isfile(python):
        python = sys.executable
    return [python, script]


def build_firmware(
    board,
    extra_args,
    overlays=(),
    build_dir=DEFAULT_BUILD_DIR,
    command="build",
    ota_repo=None,
):
    """Build firmware with idf.py.

    overlays are the sdkconfig.defaults files of the enabled features; ota_repo
    ("owner/name") replaces the default release feed of OTA updates.
    """
    print(f"\n=== Building firmware for {board} ===")
    sdkconfig_defaults = f"sdkconfig.defaults;boards/sdkconfig.defaults.{board}"
    for overlay in overlays:
        sdkconfig_defaults += f";{overlay}"
    if ota_repo:
        # Next to the build directory, which a clean build removes.
        defaults = f"{build_dir}.ota-repo.defaults"
        with open(defaults, "w", newline="\n") as out:
            out.write(f'CONFIG_FORK_OTA_REPO="{ota_repo}"\n')
        sdkconfig_defaults += f";{defaults}"

    # Boards differ in target chip (the M5Paper is a plain ESP32, everything
    # else is an ESP32-S3). Pass it explicitly: idf.py resolves the target
    # before it merges the defaults files, so CONFIG_IDF_TARGET in the board's
    # sdkconfig.defaults alone is not enough on a clean tree.
    target = BOARD_TARGET[board]

    idf_base = idf_py_command() + [
        f"-DIDF_TARGET={target}",
        f"-DSDKCONFIG_DEFAULTS={sdkconfig_defaults}",
    ]
    if build_dir != DEFAULT_BUILD_DIR:
        # A second configuration side by side (see scripts/feature_matrix.py)
        idf_base += ["-B", build_dir, f"-DSDKCONFIG={build_dir}/sdkconfig"]

    cmake_defines = [a for a in extra_args if a.startswith("-D")]
    post_build_args = [a for a in extra_args if not a.startswith("-D")]

    build_cmd = idf_base + cmake_defines + [command]
    print(f"Running: {' '.join(build_cmd)}")

    try:
        subprocess.run(build_cmd, check=True)
    except subprocess.CalledProcessError as e:
        print(f"Build failed with exit code {e.returncode}")
        sys.exit(e.returncode)
    except FileNotFoundError:
        print(
            "Error: 'idf.py' not found. Please ensure ESP-IDF is correctly installed and activated."
        )
        sys.exit(1)

    # Run post-build commands (flash, monitor, etc.)
    if post_build_args:
        post_cmd = idf_base + post_build_args
        print(f"Running: {' '.join(post_cmd)}")
        try:
            subprocess.run(post_cmd, check=True)
        except subprocess.CalledProcessError as e:
            print(f"Post-build command failed with exit code {e.returncode}")
            sys.exit(e.returncode)


def main():
    parser = argparse.ArgumentParser(description="Build firmware for different boards")
    parser.add_argument(
        "--board",
        choices=BOARDS,
        default="waveshare_photopainter_73",
        help="Board type to build",
    )
    parser.add_argument(
        "--fullclean",
        action="store_true",
        help="Remove sdkconfig and run idf.py fullclean before building",
    )
    parser.add_argument(
        "--with",
        dest="with_features",
        action="append",
        metavar="FEATURES",
        help="Enable optional features (comma separated, repeatable). Nothing is "
        "enabled by default: without any feature the build is the upstream "
        "firmware. A bundle name (extras) stands for several features. Use "
        "--list-features for the names.",
    )
    parser.add_argument(
        "--without",
        dest="without_features",
        action="append",
        metavar="FEATURES",
        help="Leave out features (mainly to trim --all-features).",
    )
    parser.add_argument(
        "--all-features",
        action="store_true",
        help="Enable every feature the board supports; the others are skipped "
        "with a warning.",
    )
    parser.add_argument(
        "--alarmclock",
        action="store_true",
        help="Same as --with alarmclock.",
    )
    parser.add_argument(
        "--build-dir",
        default=DEFAULT_BUILD_DIR,
        help="Build directory (default: build). Another one keeps its own sdkconfig, "
        "so several feature sets can be built side by side.",
    )
    parser.add_argument(
        "--ota-repo",
        metavar="OWNER/NAME",
        help="GitHub repository whose releases OTA updates are fetched from "
        "(default: upstream). A build that publishes its own releases sets it.",
    )
    parser.add_argument(
        "--list-features",
        action="store_true",
        help="List the features and whether the selected board supports them.",
    )
    parser.add_argument(
        "--step",
        choices=STEPS + OPTIONAL_STEPS,
        action="append",
        help="Run only specific step(s). Can be specified multiple times. "
        "If omitted, all steps run.",
    )
    # Allow passing extra arguments to idf.py
    args, extra_args = parser.parse_known_args()

    if args.list_features:
        print(features.describe(args.board))
        return

    steps = args.step if args.step else STEPS

    requested = features.parse_list(args.with_features)
    if args.alarmclock and "alarmclock" not in requested:
        requested.append("alarmclock")
    try:
        selection = features.resolve(
            args.board,
            requested,
            features.parse_list(args.without_features),
            args.all_features,
        )
        overlays = features.overlay_files(selection.enabled)
        if args.ota_repo:
            features.check_repo(args.ota_repo)
    except features.FeatureError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(2)

    enabled = selection.enabled
    print(f"Features for {args.board}: {', '.join(enabled) if enabled else 'none'}")
    for name, needed_by in selection.added.items():
        print(f"  + {name} (required by {needed_by})")
    for name, reason in selection.skipped.items():
        print(f"  ! skipped {name}: {reason}")
    if enabled:
        feed = args.ota_repo or "this project's release feed (--ota-repo changes it)"
        print(
            f"  note: OTA updates come from {feed}; installing one replaces this "
            "build with the release's firmware (the full-feature build of the board)."
        )

    build_state = {"board": args.board, "features": enabled}
    if args.ota_repo:
        build_state["ota_repo"] = args.ota_repo

    build_dir = args.build_dir
    if args.fullclean:
        full_clean(build_dir)
    elif ("firmware" in steps or "configure" in steps) and os.path.isdir(build_dir):
        if read_build_state(build_dir) != build_state:
            print(f"{build_dir}/ was configured for another board or feature set.")
            full_clean(build_dir)

    if "webapp" in steps:
        build_webapp(enabled)

    if "splash" in steps:
        generate_splash(args.board)

    if "configure" in steps:
        write_build_state(build_state, build_dir)
        build_firmware(
            args.board,
            extra_args,
            overlays=overlays,
            build_dir=build_dir,
            command="reconfigure",
            ota_repo=args.ota_repo,
        )

    if "firmware" in steps:
        write_build_state(build_state, build_dir)
        build_firmware(
            args.board,
            extra_args,
            overlays=overlays,
            build_dir=build_dir,
            ota_repo=args.ota_repo,
        )


if __name__ == "__main__":
    main()
